// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv9ORIULAkwdOQQmvhR9FPH0QV6kfsGW0',
    appId: '1:536578393045:web:aeaae21e804c621aed335c',
    messagingSenderId: '536578393045',
    projectId: 'realestate-41ec0',
    authDomain: 'realestate-41ec0.firebaseapp.com',
    storageBucket: 'realestate-41ec0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTP3keYusqZGN0J_ElG1sk8-XQvFkzHA0',
    appId: '1:536578393045:android:266c88300c033a48ed335c',
    messagingSenderId: '536578393045',
    projectId: 'realestate-41ec0',
    storageBucket: 'realestate-41ec0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdcbbDiY0yAmYkm7YDMW78SuC3PIiifTA',
    appId: '1:536578393045:ios:3ad499720129ef0ced335c',
    messagingSenderId: '536578393045',
    projectId: 'realestate-41ec0',
    storageBucket: 'realestate-41ec0.firebasestorage.app',
    iosBundleId: 'com.example.realestate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdcbbDiY0yAmYkm7YDMW78SuC3PIiifTA',
    appId: '1:536578393045:ios:3ad499720129ef0ced335c',
    messagingSenderId: '536578393045',
    projectId: 'realestate-41ec0',
    storageBucket: 'realestate-41ec0.firebasestorage.app',
    iosBundleId: 'com.example.realestate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv9ORIULAkwdOQQmvhR9FPH0QV6kfsGW0',
    appId: '1:536578393045:web:3a2262471fc64964ed335c',
    messagingSenderId: '536578393045',
    projectId: 'realestate-41ec0',
    authDomain: 'realestate-41ec0.firebaseapp.com',
    storageBucket: 'realestate-41ec0.firebasestorage.app',
  );
}
